version: '3.8'

services:
  postgres:
    image: postgres:15-alpine

    environment:
      POSTGRES_DB: mentee_db
      POSTGRES_USER: mentee
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mentee-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mentee-power.ru
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin