name: Java CI with Gradle

on:
  push:
    branches: [ main, feature/*, master ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Prepare
        run: chmod +x gradlew

      - name: Build without tests
        run: ./gradlew clean build -x test

      - name: Run tests
        run: ./gradlew test

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-${{ github.run_id }}
          path: build/reports/jacoco/test/html
          retention-days: 7

      - name: Clean and build
        run: ./gradlew clean build