name: CI Pipeline with TestContainers

on:
  push:
    branches: [ main, feature/*, master]
  pull_request:
    branches: [ main ]

jobs:
  test-with-testcontainers:
    runs-on: ubuntu-latest

    # 🔑 Права доступа для GITHUB_TOKEN
    permissions:
      contents: read
      checks: write
      pull-requests: write

    # ⚠️ КРИТИЧНО: Включение Docker-in-Docker
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ✅ Обязательная настройка Docker для TestContainers
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    # 🔥 ВАЖНО: Кэширование Gradle для ускорения сборки
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Prepare
      run: chmod +x gradlew

    # 🐳 КРИТИЧНО: Предзагрузка Docker образов для TestContainers
    - name: Pull TestContainers images
      run: |
        docker pull postgres:15-alpine
        docker pull testcontainers/ryuk:0.5.1

    # ✅ Проверка миграций Liquibase через Testcontainers
    - name: Validate Liquibase migrations
      run: ./gradlew liquibaseValidateCi
      env:
        TESTCONTAINERS_REUSE_ENABLE: true
        TESTCONTAINERS_CHECKS_DISABLE: true
        GRADLE_OPTS: -Xmx2g -XX:MaxMetaspaceSize=512m

    # 🧪 Запуск тестов с TestContainers
    - name: Run integration tests
      run: ./gradlew test --info
      env:
        # ⚡ Оптимизация для CI среды
        TESTCONTAINERS_REUSE_ENABLE: true
        TESTCONTAINERS_CHECKS_DISABLE: true
        # 🔧 Настройка производительности
        GRADLE_OPTS: -Xmx2g -XX:MaxMetaspaceSize=512m

    # 📊 Публикация результатов тестов
    # Пропускаем для pull requests из форков (нет доступа к check runs)
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: (success() || failure()) && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
      with:
        name: TestContainers Integration Tests
        path: 'build/test-results/test/*.xml'
        reporter: java-junit

    # 📈 Генерация и публикация отчета покрытия кода
    - name: Generate JaCoCo coverage report
      run: ./gradlew jacocoTestReport
      if: always()

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true  # Продолжить даже если файлы не найдены
      with:
        name: jacoco-report-${{ github.run_id }}
        path: build/reports/jacoco/test/html
        retention-days: 7

  # 🚀 Дополнительная задача: тестирование производительности
  # Отключена по умолчанию - включает только при необходимости
  performance-tests:
    runs-on: ubuntu-latest
    needs: test-with-testcontainers
    if: false  # Отключено по умолчанию. Чтобы включить: измените на 'true' или используйте matrix

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Prepare
      run: chmod +x gradlew

    # 🔥 Запуск производительных тестов с большим количеством памяти
    - name: Run performance tests
      run: ./gradlew test -PmaxHeapSize=4g
      env:
        # 🐳 Настройки для производительных тестов с БД
        TESTCONTAINERS_REUSE_ENABLE: true
        POSTGRES_MAX_CONNECTIONS: 200
        HIKARI_MAXIMUM_POOL_SIZE: 50
        GRADLE_OPTS: -Xmx4g -XX:MaxMetaspaceSize=1g
